#-------------------------------
# General Site Settings

menu:
# - {name: 'About', url: 'pages/about.html'}
- {name: 'Projects', url: 'pages/projects.html'}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'Contact', url: 'pages/contact.html'}
- {name: 'Resume', url: 'assets/Resume 2018-19.pdf'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  ## Who am I?

  <img src="assets/img/home/Me.jpg" alt="picture" width="300" height="300" />  

  I am a sophomore majoring in Computer Science at Georgia Tech. My undergraduate specializations lie in the fields of Artificial Intelligence and 
  Theoretical Computer Science.

  In my downtime, I like playing Cricket and Soccer, working out, and reading/watching anything that interests me in the slightest.

  ## What's going on this semester?

  Currently, I am working in Professor Daisuke Kihara's team on Protein-Protein Docking Sequence prediction using the LZeRD (Local 3D Zernike Descriptor Based
  Docking Algorithm). We are in the process of building a web application using Django for the algorithm and planning to publish a paper on it.

contact: >
  # Contact

  You may contact me [through my email](mailto:vidhur2k@gmail.com) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
- {name: 'FoodNet', folder: 'FoodNet', file: 'projects/FoodNet.html'}
- {name: 'Space Invaders', folder: 'Space-Invaders', file: 'projects/Space-Invaders.html'}
- {name: 'Pecucheck', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/vidhur2000'}
- {icon: 'instagram', link: 'https://instagram.com/vidhur2k/'}
- {icon: 'github', link: 'https://github.com/vidhur2k'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/vidhurkumar'}
- {icon: 'envelope', link: 'mailto:vidhur2k@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
